[workspace]
members = [
    "crates/channels-console",
    "crates/channels-console-test",
]
resolver = "2"

[workspace.dependencies]
channels-console = { path = "./crates/channels-console", version = "0.1.0" }
